name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Swift Package Compilation
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Swift
        run: |
          echo "Installing Swift..."
          xcode-select --install || true
          swift --version

      - name: Test Code Generator Compilation
        run: |
          echo "Testing CodeGenerator compilation..."
          cd Tools/CodeGenerator
          swift build
          echo "✅ CodeGenerator compiles successfully"

      - name: Test Generated Types Package
        run: |
          echo "Testing NearJsonRpcTypes package compilation..."
          cd Packages/NearJsonRpcTypes
          swift build
          echo "✅ NearJsonRpcTypes compiles successfully"

      - name: Test Method Mappings
        run: |
          echo "Verifying method mappings are present..."
          if [ ! -f "Packages/NearJsonRpcTypes/Methods.swift" ]; then
            echo "❌ Methods.swift not found"
            exit 1
          fi

          # Check if RpcMethod enum exists
          if ! grep -q "public enum RpcMethod" Packages/NearJsonRpcTypes/Methods.swift; then
            echo "❌ RpcMethod enum not found in Methods.swift"
            exit 1
          fi

          # Check if PATH_TO_METHOD_MAP exists
          if ! grep -q "PATH_TO_METHOD_MAP" Packages/NearJsonRpcTypes/Methods.swift; then
            echo "❌ PATH_TO_METHOD_MAP not found in Methods.swift"
            exit 1
          fi

          echo "✅ Method mappings are present and valid"

      - name: Test Generated Types
        run: |
          echo "Verifying generated types are present..."
          if [ ! -f "Packages/NearJsonRpcTypes/Types.swift" ]; then
            echo "❌ Types.swift not found"
            exit 1
          fi

          # Check if file has reasonable content
          type_count=$(grep -c "public struct\|public enum\|public typealias" Packages/NearJsonRpcTypes/Types.swift || echo "0")
          if [ "$type_count" -lt 100 ]; then
            echo "❌ Types.swift seems incomplete (only $type_count types found)"
            exit 1
          fi

          echo "✅ Generated types are present ($type_count types found)"

      - name: Run Unit Tests
        run: |
          echo "Running NearJsonRpcTypes unit tests..."
          cd Packages/NearJsonRpcTypes
          swift test --verbose
          echo "✅ All unit tests passed successfully"

      - name: Summary
        run: |
          echo "🎉 All CI tests passed!"
          echo "✅ CodeGenerator compiles"
          echo "✅ NearJsonRpcTypes package compiles"
          echo "✅ Method mappings are valid"
          echo "✅ Generated types are present"
          echo "✅ Unit tests passed"
